### ISSUE TITLE
visualize.py

### ISSUE THREAD

**Issue by akan7sha** [Karthikeyu/Indian-sign-language-recognition#3]
can u please help me with this error

Enter the csv file name to read: submission_svm.csv
Traceback (most recent call last):
  File "visualise.py", line 10, in <module>
    filename = input('Enter the csv file name to read: ')
  File "<string>", line 1, in <module>
NameError: name 'submission_svm' is not defined

**Comment by akan7sha** [comment]
resolved. thanx
