### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Harish-sy** [Karthikeyu/Indian-sign-language-recognition#5]
Traceback (most recent call last):
  File "recogniseGesture.py", line 68, in <module>
    recognise(clustering_model,classification_model)
  File "recogniseGesture.py", line 16, in recognise
    gestures = ipu.get_all_gestures()
  File "D:\Indian-sign-language-recognition-master\imagePreprocessingUtils.py", line 108, in get_all_gestures
    im_tile = concat_tile(gestures, (5, 7))
  File "D:\Indian-sign-language-recognition-master\imagePreprocessingUtils.py", line 126, in concat_tile
    imgs.append(im_list_2d[count])
IndexError: list index out of range

**Comment by poojaaap** [comment]
Did you find the solution to this problem?
