### ISSUE TITLE
while running recogniseGesture.py error is raising

### ISSUE THREAD

**Issue by MAXRIPPNER** [Karthikeyu/Indian-sign-language-recognition#7]
Traceback (most recent call last):
  File "G:\isl\recogniseGesture.py", line 66, in <module>
    clustering_model = pickle.load(open('mini_kmeans_model.sav', 'rb'))
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

**Comment by Vishal001-25** [comment]
Did you get the solution for this error?
